### ISSUE TITLE
V5 API now broken

### ISSUE THREAD

**Issue by chris64digital** [josephdouce/rubygem-BritishGasHive#1]
It looks like they have discontinued the V5 api unfortunately, so this project no longer works :( 

Any chance of an update for the v6 api?

**Comment by josephdouce** [comment]
I haven't actively developed this since I made it so I will look into, is the v6 API documentation available?

**Comment by tomcollis** [comment]
Hey, looks like it's changed quite a bit but there is some limited documentation here, if this helps?

http://www.smartofthehome.com/2016/05/hive-rest-api-v6/

**Comment by josephdouce** [comment]
V5 depreciated so this gem is no longer under development until further notice.
